Support <ARRAY-SIZE-HANDLING>
Huxelerate/autosar pull request #14
Opened 2024-02-28 16:30 UTC by andredami

2024-02-28 16:30 UTC, andredami commented
![](https://github.trello.services/images/mini-trello-icon.png) [[autosar] Support <ARRAY-SIZE-HANDLING>](https://trello.com/c/zK2hmeyf/798-autosar-support-array-size-handling)

2024-03-06 14:41 UTC, marco-rabozzi requested changes
minors

2024-03-06 14:41 UTC, marco-rabozzi commented on autosar/parser/datatype_parser.py
> +        (typeRef, arraySize, sizeHandling, sizeSemantics, arraySizeHandling) = (None, None, None, None, None)
arraySizeHandling looks unused, I think you can revert this line change

2024-03-06 14:41 UTC, marco-rabozzi commented on autosar/parser/datatype_parser.py
> +        raise ValueError(f"Invalid value for ArraySizeHandling field: {text}")
maybe enclose text in quotes so that if the xml contains invalid spaces we can detect them: ```'{text}'```

2024-03-06 17:32 UTC, marco-rabozzi approved these changes
LGTM

2024-03-06 17:32 UTC, merged