add ECUC parser
Huxelerate/autosar pull request #4
Opened 2023-08-02 11:09 UTC by acomodi

This PR adds the ECUC parser to allow getting structured information out of an ECUC arxml file

2023-08-13 14:17 UTC, marco-rabozzi requested changes

2023-08-13 14:17 UTC, marco-rabozzi commented on autosar/parser/ecu_config_parser.py
> +        definition_content = self.parseTextNode(definition_node)
if convenient, refactor this logic to handle all "DEFINITION-REF" in the same way, by fetching both the name (content) and the destination of the reference (see comment above)

2023-08-13 14:17 UTC, marco-rabozzi commented on autosar/__init__.py
> -
please undo unnecessary changes to original codebase

2023-08-13 14:21 UTC, marco-rabozzi requested changes

2023-08-13 14:21 UTC, marco-rabozzi commented on autosar/parser/ecu_config_parser.py
> +        definition = splitRef(definition)[-1] if definition is not None else None
this is not ideal, if we just take the last part of the path we are removing useful information that could be used to resolve the reference.

2023-08-13 14:21 UTC, marco-rabozzi commented on autosar/parser/ecu_config_parser.py
> +        definition_content = splitRef(self.parseTextNode(definition_node))[-1]
this is not ideal, if we just take the last part of the path we are removing useful information that could be used to resolve the reference. If needed, we can take the last part of the reference from the application logic which uses this library.

2023-08-22 07:14 UTC, acomodi commented on autosar/parser/ecu_config_parser.py
> +        definition = self.parseTextNode(node.find('DEFINITION-REF'))
added an helper function to get both definition and dest attribute

2023-08-22 08:31 UTC, marco-rabozzi requested changes

2023-08-22 08:31 UTC, marco-rabozzi commented on autosar/parser/ecu_configuration_parser.py
> +import sys
remove unused ```import sys```

2023-08-22 08:31 UTC, marco-rabozzi commented on autosar/parser/ecu_configuration_parser.py
> +from autosar.base import splitRef
remove unused ```splitRef```

2023-08-22 08:31 UTC, marco-rabozzi commented on autosar/parser/ecu_configuration_parser.py
> +        value_destination = value_node.attrib.get('DEST')
if value_node is not found, this code will raise an exception.
From the latest autosar specification I see that ```VALUE-REF``` is optional. Hence maybe here you can do: 
```
value_dest = value_node.attrib.get('DEST') if value_node else None
```

2023-08-22 08:31 UTC, marco-rabozzi commented on autosar/ecuc.py
> +            return container.find(suffix) if suffix else container
Suffix is never None, it can be an empty string. I think it is safer/cleaner to do:
```
container.find(suffix) if len(suffix) > 0 else container
```

2023-08-23 08:57 UTC, acomodi commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Platform] Add ARXML import support for tasks](https://trello.com/c/spceXxns/493-platform-add-arxml-import-support-for-tasks)

2023-08-24 06:10 UTC, merged