Feature/support included data type sets
Huxelerate/autosar pull request #8
Opened 2024-02-07 14:19 UTC by acomodi

This PR adds support for parsing the included data type sets tag in autosar > 4.0

2024-02-08 11:11 UTC, acomodi commented
![](https://github.trello.services/images/mini-trello-icon.png) [[autosar-sil] support INCLUDED-DATA-TYPE-FIELDS, SW-CALPRM-AXIS-SET, SW-RECORD-LAYOUT-REF, VALUE-AXIS-DATA-TYPE-REF](https://trello.com/c/1EUrjq8O/750-autosar-sil-support-included-data-type-fields-sw-calprm-axis-set-sw-record-layout-ref-value-axis-data-type-ref)

2024-02-09 15:17 UTC, marco-rabozzi requested changes

2024-02-09 15:17 UTC, marco-rabozzi commented on autosar/parser/behavior_parser.py
> +        data_type_refs = xmlRoot.find('DATA-TYPE-REFS')
from the specification, DATA-TYPE-REFS might not be present. If so, it might be safe to early return a list of empty data type refs.

2024-02-09 15:17 UTC, marco-rabozzi commented on autosar/parser/behavior_parser.py
> +        data_type_refs = xmlRoot.find('DATA-TYPE-REFS')
use camel case style to conform with the library style (please check all changes)

2024-02-09 15:17 UTC, marco-rabozzi commented on autosar/behavior.py
> +        self.included_datatype_sets = []
I think it is worth adding a INCLUDED-DATA-TYPE-SET object, since a INCLUDED-DATA-TYPE-SET is not just a collection of type references, but it also allow to specify the LITERAL-PREFIX property (double check the autosar xsd). See a public example here:
[https://github.com/autosaros/Standards/blob/7be1549a5f084f2ddf598f4d40d8df84cb057cf7/Classic%20Platform/4.4.0/MethodologyAndTemplates/AUTOSAR_EXP_ModelingShowCases/30_MeasurementCalibration/20_Advanced/CMscB.arxml#L199](https://github.com/autosaros/Standards/blob/7be1549a5f084f2ddf598f4d40d8df84cb057cf7/Classic%20Platform/4.4.0/MethodologyAndTemplates/AUTOSAR_EXP_ModelingShowCases/30_MeasurementCalibration/20_Advanced/CMscB.arxml#L199)

2024-02-10 16:48 UTC, marco-rabozzi approved these changes
LGTM

2024-02-10 16:49 UTC, merged